### ISSUE TITLE
Can't finish deleting a pipeline

### ISSUE THREAD

**Issue by pomozoff** [anodot/daria#492]
The process of a pipeline deletion was cancelled and I can not finish deletion anymore:
```
agent@agent:/usr/src/app$ agent pipeline list
2023-05-11 07:49:08,206 - INFO - Get pipeline statuses
Name                                                     Type         Status   Streamsets URL
==============================================================================================
my_pipeline                                              clickhouse   RETRY    http://dc:18630
agent@agent:/usr/src/app$ agent pipeline delete my_pipeline
Traceback (most recent call last):
  File "/usr/local/bin/agent", line 33, in <module>
    sys.exit(load_entry_point('agent==3.49.4', 'console_scripts', 'agent')())
  File "/usr/local/lib/python3.10/site-packages/agent-3.49.4-py3.10.egg/agent/cli/__init__.py", line 39, in agent_entry_point
    agent()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/agent-3.49.4-py3.10.egg/agent/cli/pipeline.py", line 184, in delete
    pipeline.manager.delete_by_id(pipeline_id, delete_metrics=delete_metrics)
  File "/usr/local/lib/python3.10/site-packages/agent-3.49.4-py3.10.egg/agent/pipeline/manager.py", line 246, in delete_by_id
    delete(pipeline.repository.get_by_id(pipeline_id))
  File "/usr/local/lib/python3.10/site-packages/agent-3.49.4-py3.10.egg/agent/pipeline/manager.py", line 234, in delete
    _delete_schema(pipeline_)
  File "/usr/local/lib/python3.10/site-packages/agent-3.49.4-py3.10.egg/agent/pipeline/manager.py", line 214, in _delete_schema
    schema.delete(pipeline_.get_schema_id())
  File "/usr/local/lib/python3.10/site-packages/agent-3.49.4-py3.10.egg/agent/pipeline/schema.py", line 71, in delete
    AnodotApiClient(destination.repository.get()).delete_schema(schema_id)
  File "/usr/local/lib/python3.10/site-packages/agent-3.49.4-py3.10.egg/agent/destination/anodot_api_client.py", line 36, in wrapper
    return process_response(func(*args, **kwargs))
  File "/usr/local/lib/python3.10/site-packages/agent-3.49.4-py3.10.egg/agent/destination/anodot_api_client.py", line 23, in process_response
    res.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://my_company.anodot.com/api/v2/stream-schemas/1d4e3936-ae35-408e-b8d4-282b4f3f66f9
```

**Comment by pomozoff** [comment]
I just removed a record describing this pipeline from the db table.
